version: "3.9"
services:
  frontend_web:
    image: nginx
    env_file: 
      - ./my-stack.env  
    ports:
      - 80:80  
  backend1_api:
    image: nginx 
    env_file: 
      - ./my-stack.env
    ports:
      - 8081:8081
  backend2_api:
    image: nginx
    env_file:
      - ./my-stack.env
    ports:      
      - 8082:8082
  postgredb:
    image: postgres:11.13-alpine3.14
    volumes:
      - ./pgdb/initdb:/docker-entrypoint-initdb.d
    env_file: 
      - ./my-stack.env
    ports:
      - 5432:5432
  redis_cachedb:
    image: redis:4
    env_file: 
      - ./my-stack.env
    ports:
      - 6379:6379
      